[build]
  base = "."
  command = """
    curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.16.4-stable.tar.xz && 
    tar xf flutter_linux_3.16.4-stable.tar.xz && 
    export PATH="$PATH:`pwd`/flutter/bin" && 
    flutter precache && 
    flutter config --enable-web && 
    flutter build web --release --web-renderer html
  """
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.16.4"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false 